{ config, ... }:

let
    colors = config.style.colors;
in {
    config = {
        home.file.".config/tint2/tint2rc".source = builtins.toFile "tint2rc" ''
            #---- Generated by tint2conf a212 ----
            # See https://gitlab.com/o9000/tint2/wikis/Configure for 
            # full documentation of the configuration options.
            #-------------------------------------
            # Backgrounds
            # Background 1: Active taskbar, Battery, Clock, Launcher, Systray, Tooltip
            rounded = 0
            border_width = 0
            background_color = #222222 100
            border_color = #222222 0
            background_color_hover = #222222 100
            border_color_hover = #222222 0
            background_color_pressed = #222222 100
            border_color_pressed = #222222 0

            # Background 2: Active task
            rounded = 0
            border_width = 0
            background_color = #444444 100
            border_color = #444444 0
            background_color_hover = #444444 100
            border_color_hover = #444444 0
            background_color_pressed = #444444 100
            border_color_pressed = #444444 0

            # Background 3: Urgent task
            rounded = 0
            border_width = 0
            background_color = #d98282 100
            border_color = #d98282 0
            background_color_hover = #d98282 100
            border_color_hover = #d98282 0
            background_color_pressed = #d98282 100
            border_color_pressed = #d98282 0

            # Background 4: Default task
            rounded = 0
            border_width = 0
            background_color = #333333 100
            border_color = #333333 0
            background_color_hover = #333333 100
            border_color_hover = #333333 0
            background_color_pressed = #333333 100
            border_color_pressed = #333333 0

            # Background 5: Iconified task
            rounded = 0
            border_width = 0
            background_color = #252525 100
            border_color = #252525 0
            background_color_hover = #252525 100
            border_color_hover = #252525 0
            background_color_pressed = #252525 100
            border_color_pressed = #252525 0

            # Background 6: Start Button
            rounded = 0
            border_width = 0
            background_color = ${colors.color1} 100
            border_color = ${colors.color1} 0

            #-------------------------------------
            # Panel
            panel_items = PTSBC
            panel_size = 100% 40
            panel_margin = 0 0
            panel_padding = 0 0 0
            panel_background_id = 0
            wm_menu = 1
            panel_dock = 0
            panel_position = bottom center horizontal
            panel_layer = top
            panel_monitor = 2
            primary_monitor_first = 0
            autohide = 0
            autohide_show_timeout = 0.3
            autohide_hide_timeout = 1.5
            autohide_height = 6
            strut_policy = follow_size
            panel_window_name = tint2
            disable_transparency = 0
            mouse_effects = 0
            font_shadow = 0
            mouse_hover_icon_asb = 100 0 10
            mouse_pressed_icon_asb = 100 0 0

            #-------------------------------------
            # Button
            button = new
            button_text = 
            button_background_id = 6
            button_font_color = ${colors.background} 100
            button_padding = 15 15 0
            button_centered = 1
            button_font = Anonymice 38

            #-------------------------------------
            # Taskbar
            taskbar_mode = single_desktop
            taskbar_padding = 0 0 0
            taskbar_background_id = 0
            taskbar_active_background_id = 1
            taskbar_name = 0
            taskbar_hide_inactive_tasks = 0
            taskbar_hide_different_monitor = 0
            taskbar_always_show_all_desktop_tasks = 0
            taskbar_name_padding = 0 0
            taskbar_name_background_id = 0
            taskbar_name_active_background_id = 0
            taskbar_name_font = Anonymice r 8
            taskbar_name_font_color = #d1d1d1 100
            taskbar_name_active_font_color = #888888 100
            taskbar_distribute_size = 0
            taskbar_sort_order = none
            task_align = left

            #-------------------------------------
            # Task
            task_text = 0
            task_icon = 1
            task_centered = 1
            urgent_nb_of_blink = 20
            task_maximum_size = 75 75
            task_padding = 8 6 8
            task_font = Anonymice r 9
            task_tooltip = 1
            task_thumbnail = 1
            task_font_color = #d1d1d1 100
            task_active_font_color = #d1d1d1 100
            task_urgent_font_color = #d1d1d1 100
            task_iconified_font_color = #d1d1d1 80
            task_icon_asb = 100 0 0
            task_active_icon_asb = 100 0 0
            task_urgent_icon_asb = 100 0 0
            task_iconified_icon_asb = 80 0 0
            task_background_id = 4
            task_active_background_id = 2
            task_urgent_background_id = 3
            task_iconified_background_id = 5
            mouse_left = toggle_iconify
            mouse_middle = close
            mouse_right = none
            mouse_scroll_up = none
            mouse_scroll_down = none

            #-------------------------------------
            # System tray (notification area)
            systray_padding = 8 0 12
            systray_background_id = 1
            systray_sort = right2left
            systray_icon_size = 18
            systray_icon_asb = 100 0 0
            systray_monitor = 1

            #-------------------------------------
            # Clock
            time1_format = %H:%M
            time2_format = 
            time1_font = Anonymice r bold 9
            clock_font_color = #d1d1d1 100
            clock_padding = 8 4
            clock_background_id = 1

            #-------------------------------------
            # Battery
            battery_tooltip = 1
            battery_low_status = 20
            battery_low_cmd = notify-send "battery low"
            bat1_font = Anonymice r 8
            bat2_font = Anonymice r 7
            battery_font_color = #d1d1d1 100
            battery_padding = 2 0
            battery_background_id = 1
            battery_hide = 96
            battery_lclick_command = 
            battery_rclick_command = 
            battery_mclick_command = 
            battery_uwheel_command = 
            battery_dwheel_command = 
            ac_connected_cmd = 
            ac_disconnected_cmd = 

            #-------------------------------------
            # Tooltip
            tooltip_show_timeout = 1
            tooltip_hide_timeout = 0
            tooltip_padding = 6 6
            tooltip_background_id = 1
            tooltip_font_color = #d1d1d1 100
            tooltip_font = envy code r 8
        '';
    };
}